### ISSUE TITLE
fetchAndReset() broken with git submodules

### ISSUE THREAD

**Issue by stevendgonzales** [srinivasupadhya/git-cmd#1]
When using gocd-build-github-pull-requests with a repo with git submodules and over SSH, the call to `fetchAndReset()` raises exception as documented here: https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/31

```
2015-05-16 06:11:44,640  WARN [84@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:67 - get latest revisions since:
java.lang.RuntimeException: Exception Occurred: [git, config, --get-regexp, ^submodule\..+\.url] - /var/lib/go-server/pipelines/flyweight/3d83eae3-92a0-4b48-83b5-8a72e7d44e8d
    at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
    at com.tw.go.plugin.git.GitCmdHelper.runAndGetOutput(GitCmdHelper.java:386)
    at com.tw.go.plugin.git.GitCmdHelper.submoduleUrls(GitCmdHelper.java:233)
    at com.tw.go.plugin.git.GitCmdHelper.cleanAllUnversionedFiles(GitCmdHelper.java:211)
    at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:100)
    at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:95)
    at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
    at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleLatestRevisionSince(GitHubPRBuildPlugin.java:185)
    at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:83)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
    at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
    at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
    at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
    at com.thoughtworks.go.plugin.access.scm.SCMExtension.latestModificationSince(SCMExtension.java:154)
    at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:77)
    at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:46)
    at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
    at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
    at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.insertLatestOrNewModifications(PluggableSCMMaterialUpdater.java:61)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
    at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
    at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
    at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
    at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
    at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
```

[fetchAndReset()](https://github.com/srinivasupadhya/git-cmd/blob/master/src/com/tw/go/plugin/GitHelper.java#L98) immediately calls [cleanAllUnversionedFiles()](https://github.com/srinivasupadhya/git-cmd/blob/master/src/com/tw/go/plugin/git/GitCmdHelper.java#L208)
cleanAllUnversionedFiles() make a call to [submoduleUrls()](https://github.com/srinivasupadhya/git-cmd/blob/master/src/com/tw/go/plugin/git/GitCmdHelper.java#L231) which makes the call `git config --get-regexp ^submodule\\..+\\.url` to return the urls for all submodules, which FAILS because submodules must be initialized for that call to work.

The issue is that cleanAllUnversionedFiles check for submodules simply by looking for the config, but does not check to see that they are inittialized before calling submoduleUrls()

Potential fix is to add a call to `submoduleInit()` inside of fetchAndReset() before the first call to cleanAllUnversionedFiles():

``` java
public void fetchAndReset(String revision, String refSpec) {
        stdOut.consumeLine(String.format("[GIT] Fetch and reset in working directory %s", workingDir));
        submoduleInit();
        cleanAllUnversionedFiles();
        if (isSubmoduleEnabled()) {
            removeSubmoduleSectionsFromGitConfig();
        }
        fetch(refSpec);
        gc();
        resetHard(revision);
        if (isSubmoduleEnabled()) {
            checkoutAllModifiedFilesInSubmodules();
            updateSubmoduleWithInit();
        }
        cleanAllUnversionedFiles();
    }
```

**Comment by stevendgonzales** [comment]
^^ If you like that fix I can send as a PR

**Comment by srinivasupadhya** [comment]
Im doing what Go does [here](https://github.com/gocd/gocd/blob/42c619e40adad3c3b25e1de43c962cf896772d93/common/src/com/thoughtworks/go/domain/materials/git/GitCommand.java#L122). Will try to reproduce the problem & fix it. Thanks for the solution :+1:

**Comment by stevendgonzales** [comment]
The unit test for this is broken also:

```
est set: com.tw.go.plugin.git.GitCmdHelperTest
-------------------------------------------------------------------------------
Tests run: 12, Failures: 1, Errors: 1, Skipped: 1, Time elapsed: 1.514 sec <<< FAILURE!
shouldPollRepository(com.tw.go.plugin.git.GitCmdHelperTest)  Time elapsed: 0.222 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <3>
     but: was <1>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at org.junit.Assert.assertThat(Assert.java:832)
    at com.tw.go.plugin.AbstractGitHelperTest.shouldPollRepository(AbstractGitHelperTest.java:117)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
shouldRecursiveSubModuleUpdate(com.tw.go.plugin.git.GitCmdHelperTest)  Time elapsed: 0.187 sec  <<< ERROR!
java.lang.RuntimeException: Exception Occurred: [git, config, --get-regexp, ^submodule\..+\.url] - /var/folders/zk/kys2l48d7qs0xq_f3jvt_8fm0000gn/T/24d06e7c-d408-4057-8423-b0e51687fed4
    at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
    at com.tw.go.plugin.git.GitCmdHelper.runAndGetOutput(GitCmdHelper.java:386)
    at com.tw.go.plugin.git.GitCmdHelper.submoduleUrls(GitCmdHelper.java:233)
    at com.tw.go.plugin.git.GitCmdHelper.cleanAllUnversionedFiles(GitCmdHelper.java:211)
    at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:100)
    at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:95)
    at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
    at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:32)
    at com.tw.go.plugin.AbstractGitHelperTest.shouldRecursiveSubModuleUpdate(AbstractGitHelperTest.java:171)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
    at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
    ... 39 more
```

**Comment by srinivasupadhya** [comment]
fixed in https://github.com/srinivasupadhya/git-cmd/commit/92b2f188374200145bfc00dc89533c6269c5fc95.
Thanks for reporting. Will make a release of [gocd-build-github-pull-requests](https://github.com/ashwanthkumar/gocd-build-github-pull-requests) with this change soon.
